[build]
  command = "npm run build:lib && npm run build:demo"
  publish = "dist/demo-app/browser"

[build.environment]
  ANGULAR_PROJECT = "demo-app"

[[plugins]]
  package = "@netlify/angular-runtime"